"""empty message

Revision ID: 00a5be79f9e5
Revises: 1fc0db149ce4
Create Date: 2016-03-15 18:38:03.065255

"""

# revision identifiers, used by Alembic.
revision = '00a5be79f9e5'
down_revision = '1fc0db149ce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen_at', sa.String(), nullable=True))
    op.drop_column('user', 'last_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_seen_at')
    ### end Alembic commands ###
