"""empty message

Revision ID: 132638927a0c
Revises: c70c6f196404
Create Date: 2016-03-15 20:54:44.760594

"""

# revision identifiers, used by Alembic.
revision = '132638927a0c'
down_revision = 'c70c6f196404'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blog_comment_blog_id'), 'blog_comment', ['blog_id'], unique=False)
    op.create_foreign_key('fk_blogcomment_blog', 'blog_comment', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_blogcomment_blog', 'blog_comment', type_='foreignkey')
    op.drop_index(op.f('ix_blog_comment_blog_id'), table_name='blog_comment')
    op.drop_column('blog_comment', 'blog_id')
    ### end Alembic commands ###
