"""empty message

Revision ID: 1fc0db149ce4
Revises: 2705971e06d5
Create Date: 2016-03-14 21:40:49.396567

"""

# revision identifiers, used by Alembic.
revision = '1fc0db149ce4'
down_revision = '2705971e06d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_member_theme', 'user', 'site_theme', ['theme_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_member_theme', 'user', type_='foreignkey')
    op.drop_column('user', 'theme_id')
    ### end Alembic commands ###
