"""empty message

Revision ID: 2705971e06d5
Revises: cf1dc80020bb
Create Date: 2016-03-14 21:35:54.935216

"""

# revision identifiers, used by Alembic.
revision = '2705971e06d5'
down_revision = 'cf1dc80020bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_theme', sa.Column('css_file', sa.String(), nullable=True))
    op.drop_column('site_theme', 'css')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_theme', sa.Column('css', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('site_theme', 'css_file')
    ### end Alembic commands ###
