"""empty message

Revision ID: 29578f1311a2
Revises: 2be390c376f1
Create Date: 2016-03-02 19:07:32.409418

"""

# revision identifiers, used by Alembic.
revision = '29578f1311a2'
down_revision = '2be390c376f1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_message', sa.Column('last_seen_by', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_message', 'last_seen_by')
    ### end Alembic commands ###
