"""empty message

Revision ID: 2be390c376f1
Revises: b016466b43d6
Create Date: 2016-02-25 20:44:03.598378

"""

# revision identifiers, used by Alembic.
revision = '2be390c376f1'
down_revision = 'b016466b43d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('legacy_password', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'legacy_password')
    ### end Alembic commands ###
