"""empty message

Revision ID: 3356258ed6c8
Revises: fab503f7a265
Create Date: 2016-03-20 14:18:31.559851

"""

# revision identifiers, used by Alembic.
revision = '3356258ed6c8'
down_revision = 'fab503f7a265'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_phrase', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phrase_last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phrase_last_updated')
    op.drop_column('user', 'favorite_phrase')
    ### end Alembic commands ###
