"""empty message

Revision ID: 3811d88562b9
Revises: 6c86d3cf95f9
Create Date: 2016-02-21 09:16:28.775915

"""

# revision identifiers, used by Alembic.
revision = '3811d88562b9'
down_revision = '6c86d3cf95f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_status_update_created'), 'status_update', ['created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_update_created'), table_name='status_update')
    ### end Alembic commands ###
