"""empty message

Revision ID: 479f4c068f23
Revises: None
Create Date: 2016-03-19 09:45:50.717520

"""

# revision identifiers, used by Alembic.
revision = '479f4c068f23'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('featured', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'featured')
    ### end Alembic commands ###
