"""empty message

Revision ID: 6186cfb56a76
Revises: ff7af881077d
Create Date: 2016-02-25 20:31:55.842859

"""

# revision identifiers, used by Alembic.
revision = '6186cfb56a76'
down_revision = 'ff7af881077d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('legacy_password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'legacy_password')
    ### end Alembic commands ###
