"""empty message

Revision ID: 6c86d3cf95f9
Revises: 9e2b567c47df
Create Date: 2016-02-10 19:19:37.111495

"""

# revision identifiers, used by Alembic.
revision = '6c86d3cf95f9'
down_revision = '9e2b567c47df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_created'), 'post', ['created'], unique=False)
    op.create_index(op.f('ix_post_hidden'), 'post', ['hidden'], unique=False)
    op.create_index(op.f('ix_post_topic_id'), 'post', ['topic_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_topic_id'), table_name='post')
    op.drop_index(op.f('ix_post_hidden'), table_name='post')
    op.drop_index(op.f('ix_post_created'), table_name='post')
    ### end Alembic commands ###
