"""empty message

Revision ID: 6ed81d9380d5
Revises: 3356258ed6c8
Create Date: 2016-03-20 16:32:46.868687

"""

# revision identifiers, used by Alembic.
revision = '6ed81d9380d5'
down_revision = '3356258ed6c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('smileys_last_updated', sa.DateTime(), nullable=True))
    op.drop_column('user', 'favorite_phrase')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_phrase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'smileys_last_updated')
    ### end Alembic commands ###
