"""empty message

Revision ID: 6ef96a2a8201
Revises: 94fe39e6cda4
Create Date: 2016-02-06 20:06:54.003184

"""

# revision identifiers, used by Alembic.
revision = '6ef96a2a8201'
down_revision = '94fe39e6cda4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hidden', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hidden')
    ### end Alembic commands ###
