"""empty message

Revision ID: 6f9b34f86678
Revises: c38410949adc
Create Date: 2016-03-13 08:33:56.405484

"""

# revision identifiers, used by Alembic.
revision = '6f9b34f86678'
down_revision = 'c38410949adc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('t_title', sa.String(), nullable=True))
    op.add_column('private_message_reply', sa.Column('pm_title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_message_reply', 'pm_title')
    op.drop_column('post', 't_title')
    ### end Alembic commands ###
