"""empty message

Revision ID: 70ec112d9bcd
Revises: 3811d88562b9
Create Date: 2016-02-21 09:24:48.855111

"""

# revision identifiers, used by Alembic.
revision = '70ec112d9bcd'
down_revision = '3811d88562b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_topic_created'), 'topic', ['created'], unique=False)
    op.create_index(op.f('ix_user_banned'), 'user', ['banned'], unique=False)
    op.create_index(op.f('ix_user_hidden_last_seen'), 'user', ['hidden_last_seen'], unique=False)
    op.create_index(op.f('ix_user_joined'), 'user', ['joined'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_joined'), table_name='user')
    op.drop_index(op.f('ix_user_hidden_last_seen'), table_name='user')
    op.drop_index(op.f('ix_user_banned'), table_name='user')
    op.drop_index(op.f('ix_topic_created'), table_name='topic')
    ### end Alembic commands ###
