"""empty message

Revision ID: 74a97255bd9e
Revises: 29578f1311a2
Create Date: 2016-03-07 18:52:04.467764

"""

# revision identifiers, used by Alembic.
revision = '74a97255bd9e'
down_revision = '29578f1311a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('default_avatar_id', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('default_gallery_image_id', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('legacy_avatar_field', sa.String(), nullable=True))
    op.add_column('character', sa.Column('legacy_gallery_field', sa.String(), nullable=True))
    op.create_foreign_key('fk_character_default_gallery', 'character', 'attachment', ['default_gallery_image_id'], ['id'])
    op.create_foreign_key('fk_character_default_avatar', 'character', 'attachment', ['default_avatar_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_character_default_avatar', 'character', type_='foreignkey')
    op.drop_constraint('fk_character_default_gallery', 'character', type_='foreignkey')
    op.drop_column('character', 'legacy_gallery_field')
    op.drop_column('character', 'legacy_avatar_field')
    op.drop_column('character', 'default_gallery_image_id')
    op.drop_column('character', 'default_avatar_id')
    ### end Alembic commands ###
