"""empty message

Revision ID: 75fc254a4436
Revises: 270079cc571a
Create Date: 2016-02-23 18:36:45.035168

"""

# revision identifiers, used by Alembic.
revision = '75fc254a4436'
down_revision = '270079cc571a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notification_preferences', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notification_preferences')
    ### end Alembic commands ###
