"""empty message

Revision ID: 91ef1e1f1767
Revises: 6f9b34f86678
Create Date: 2016-03-13 09:55:53.287053

"""

# revision identifiers, used by Alembic.
revision = '91ef1e1f1767'
down_revision = '6f9b34f86678'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_online', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_online')
    ### end Alembic commands ###
