"""empty message

Revision ID: 94fe39e6cda4
Revises: 6b760e70139e
Create Date: 2016-02-06 16:09:09.711322

"""

# revision identifiers, used by Alembic.
revision = '94fe39e6cda4'
down_revision = '6b760e70139e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_message', sa.Column('last_reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_pm_lastreply', 'private_message', 'private_message_reply', ['last_reply_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pm_lastreply', 'private_message', type_='foreignkey')
    op.drop_column('private_message', 'last_reply_id')
    ### end Alembic commands ###
