"""empty message

Revision ID: 9e2b567c47df
Revises: 6ef96a2a8201
Create Date: 2016-02-09 19:25:14.927944

"""

# revision identifiers, used by Alembic.
revision = '9e2b567c47df'
down_revision = '6ef96a2a8201'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('last_seen_by', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'last_seen_by')
    ### end Alembic commands ###
