"""empty message

Revision ID: b016466b43d6
Revises: f4829e461908
Create Date: 2016-02-25 20:43:51.794166

"""

# revision identifiers, used by Alembic.
revision = 'b016466b43d6'
down_revision = 'f4829e461908'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'legacy_password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('legacy_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
