"""empty message

Revision ID: b41a46db3f17
Revises: None
Create Date: 2016-03-15 20:41:52.037713

"""

# revision identifiers, used by Alembic.
revision = 'b41a46db3f17'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_entry', sa.Column('published', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_blog_entry_published'), 'blog_entry', ['published'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_entry_published'), table_name='blog_entry')
    op.drop_column('blog_entry', 'published')
    ### end Alembic commands ###
