"""empty message

Revision ID: b6b0a15b2aa6
Revises: 6ed81d9380d5
Create Date: 2016-03-20 17:16:32.902829

"""

# revision identifiers, used by Alembic.
revision = 'b6b0a15b2aa6'
down_revision = '6ed81d9380d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_boops_from_users_post_id'), 'post_boops_from_users', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_boops_from_users_user_id'), 'post_boops_from_users', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_boops_from_users_user_id'), table_name='post_boops_from_users')
    op.drop_index(op.f('ix_post_boops_from_users_post_id'), table_name='post_boops_from_users')
    ### end Alembic commands ###
