"""empty message

Revision ID: c70c6f196404
Revises: b41a46db3f17
Create Date: 2016-03-15 20:50:09.478558

"""

# revision identifiers, used by Alembic.
revision = 'c70c6f196404'
down_revision = 'b41a46db3f17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_entry', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_entry', 'title')
    ### end Alembic commands ###
