"""empty message

Revision ID: cbd7806fd843
Revises: 6186cfb56a76
Create Date: 2016-02-25 20:37:39.863984

"""

# revision identifiers, used by Alembic.
revision = 'cbd7806fd843'
down_revision = '6186cfb56a76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ipb_salt', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ipb_salt')
    ### end Alembic commands ###
