"""empty message

Revision ID: cf1dc80020bb
Revises: 91ef1e1f1767
Create Date: 2016-03-14 19:45:56.414429

"""

# revision identifiers, used by Alembic.
revision = 'cf1dc80020bb'
down_revision = '91ef1e1f1767'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['role'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    ### end Alembic commands ###
