"""empty message

Revision ID: d1ed55e64bc8
Revises: 70ec112d9bcd
Create Date: 2016-02-21 09:31:00.443930

"""

# revision identifiers, used by Alembic.
revision = 'd1ed55e64bc8'
down_revision = '70ec112d9bcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_status_update_author_id'), 'status_update', ['author_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_update_author_id'), table_name='status_update')
    ### end Alembic commands ###
