"""empty message

Revision ID: f4829e461908
Revises: cbd7806fd843
Create Date: 2016-02-25 20:38:44.053636

"""

# revision identifiers, used by Alembic.
revision = 'f4829e461908'
down_revision = 'cbd7806fd843'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ipb_hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ipb_hash')
    ### end Alembic commands ###
