"""empty message

Revision ID: f8e3872c30e7
Revises: 479f4c068f23
Create Date: 2016-03-19 09:47:36.092608

"""

# revision identifiers, used by Alembic.
revision = 'f8e3872c30e7'
down_revision = '479f4c068f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'featured')
    op.add_column('blog_entry', sa.Column('featured', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_entry', 'featured')
    op.add_column('blog', sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
