"""empty message

Revision ID: fab503f7a265
Revises: None
Create Date: 2016-03-20 13:43:37.849349

"""

# revision identifiers, used by Alembic.
revision = 'fab503f7a265'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_entry_subscribers',
    sa.Column('blogentry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blogentry_id'], ['blog_entry.id'], name='fk_subscriber_blog_entry', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_subscriber_user_blog_entry', ondelete='CASCADE')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_entry_subscribers')
    ### end Alembic commands ###
