"""empty message

Revision ID: ff7af881077d
Revises: 75fc254a4436
Create Date: 2016-02-24 20:48:43.672367

"""

# revision identifiers, used by Alembic.
revision = 'ff7af881077d'
down_revision = '75fc254a4436'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fingerprint', sa.Column('fingerprint_hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fingerprint', 'fingerprint_hash')
    ### end Alembic commands ###
